#Email Server Details
emai.from=noreply@gmail.com
mail.host=smtp.intra.gmail.com
mail.mail_username = user
mail.mail_password = password
mail.port = 8080

#=======================================================

#Email SPOC Details
email.to = mchaudhari767@gmail.com
startemail.to = mchaudhari767@gmail.com
#=======================================================

#EMAIL SUBJECT LINE
email.subject = Automated Functional Test Report for Project_1- Suite <Date>
startemail.subject = Automated Functional Test Execution Reports for Project_1 Suite-1
#=======================================================

#EMAIL CONTENT
email.content = Hi All,\n Please find the below Automated Functional Test Suite Execution Report for Project_1 application. \n\n
startemail.content = Hi All, \n Please find the below Automated Functional Test Suite Execution Report_1 is triggered on <SERVER URL>  URL for below.