browser = edge
pageLoadTimeout = 20
implicitlyWait = 30

nfs_username = admin
nfs_password = admin
nfs_IP = 192.1.0.0
nfs_port = 8080
initialise_report_path = /apps/automationReports/reports/
nfs_shellscript = /apps/automationReports/scripts/email.sh


environmentName = Environment Details
testEnv = TEST
testType = Automation Test Suite
testName = Functional Test Suite on TEST Environment

buildVersionName = @Build Version
buildVersionNumber = v1.0
releaseVersionName = @Release Version
releaseVersionNumber = MONTHLY RELEASE 2025
qa = QA Name
qaName = MAHENDRA

